name = "BouncingBall"
uuid = "6ce5e8f0-9515-4679-a116-e9dd2bf17cd2"
authors = ["Lilith Hafner <Lilith.Hafner@gmail.com> and contributors"]
version = "0.0.0"

[deps]
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"

[compat]
Gtk = "1.2.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
